export const PROMOTION_TYPES = {
  percentage: {
    value: "percentage",
    label: "Percentage Discount",
    description: "Discount by percentage",
    icon: "fa-percent",
    color: "blue",
    fields: ["value", "min_order_amount", "max_discount_amount"],
    example: "20% off all items",
  },
  fixed: {
    value: "fixed",
    label: "Fixed Amount Off",
    description: "Fixed amount discount",
    icon: "fa-tag",
    color: "purple",
    fields: ["value", "min_order_amount"],
    example: "₱500 off your purchase",
  },
  bogo: {
    value: "bogo",
    label: "Buy One Get One",
    description: "Buy 1 item, get 1 free",
    icon: "fa-gift",
    color: "green",
    fields: ["free_menu_item_id", "required_menu_item_id"],
    example: "Buy 1 Pizza, Get 1 Free",
  },
  free_gift: {
    value: "free_gift",
    label: "Free Gift",
    description: "Get free item with purchase",
    icon: "fa-gift",
    color: "pink",
    fields: ["free_gift_product_id", "min_order_amount"],
    example: "Free drink with ₱1000 purchase",
  },
  bundle: {
    value: "bundle",
    label: "Bundle Deal",
    description: "Buy multiple items at discount",
    icon: "fa-layer-group",
    color: "indigo",
    fields: ["buy_quantity", "get_quantity", "get_discount_percentage"],
    example: "Buy 2, Get 3rd at 50%",
  },
  tiered: {
    value: "tiered",
    label: "Tiered Discount",
    description: "Discount based on amount spent",
    icon: "fa-layer-group",
    color: "orange",
    fields: ["tiers"],
    example: "₱100 off ₱1000, ₱300 off ₱3000",
  },
  free_shipping: {
    value: "free_shipping",
    label: "Free Shipping",
    description: "Free delivery",
    icon: "fa-truck",
    color: "teal",
    fields: ["min_order_amount"],
    example: "Free shipping on ₱500+ orders",
  },
  loyalty_points: {
    value: "loyalty_points",
    label: "Loyalty Points",
    description: "Earn points per purchase",
    icon: "fa-star",
    color: "yellow",
    fields: ["points_multiplier", "min_order_amount"],
    example: "10 points per ₱100 spent",
  },
  buy_x_get_y: {
    value: "buy_x_get_y",
    label: "Buy X Get Y",
    description: "Buy X get Y at discount",
    icon: "fa-shopping-bag",
    color: "cyan",
    fields: ["buy_quantity", "get_quantity", "get_discount_percentage"],
    example: "Buy 2 Get 1 Free",
  },
  first_purchase: {
    value: "first_purchase",
    label: "First Purchase",
    description: "New customer discount",
    icon: "fa-user-plus",
    color: "emerald",
    fields: ["value", "min_order_amount"],
    example: "15% off first order",
  },
  flash_sale: {
    value: "flash_sale",
    label: "Flash Sale",
    description: "Limited time offer",
    icon: "fa-bolt",
    color: "red",
    fields: ["value", "min_order_amount", "max_discount_amount"],
    example: "30% off for 24 hours",
  },
};

export const PROMOTION_TYPE_OPTIONS = Object.values(PROMOTION_TYPES);
